import vazirFont from "@/constants/localFonts";
import Header from "./Header";
import "./globals.css";

export const metadata = {
  title: "Next Shop Panel",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirFont.variable} font-sans`}>
        <Header />
        <div className="container xl:max-w-screen-xl">{children}</div>
      </body>
    </html>
  );
}
